### ISSUE TITLE
zosconnect api list command results in unknown errors

### ISSUE THREAD

**Issue by DivergentEuropeans** [zosconnect/zowe-cli-zosconnect-plugin#83]
Hello, We installed the z/OS Connect plugin for the Zowe CLI. However, when we went to issue a basic command - list apis, we are getting a security error. I will be attaching the doc that shows the profile I created, I tried both 
zowe zosconnect api list
and
zowe zosconnect api list --rfj (this one is shown in logs), 
the output from the different sections of the z/OS Connect task, and a screen capture of the same URL working from a web browser (.docx below). 

[Zowe_-_zOS_Connect_Profile (1).docx](https://github.com/zosconnect/zowe-cli-zosconnect-plugin/files/7342199/Zowe_-_zOS_Connect_Profile.1.docx)

Can we get help on what we are missing to make this work. I have enabled tracing for both imperative and zowe log, but I do not see anything useful; attaching them here. Username, password, and address changed for confidentiality

[imperative-10042021 (1).log](https://github.com/zosconnect/zowe-cli-zosconnect-plugin/files/7342178/imperative-10042021.1.log)
[zowe-10042021 (1).log](https://github.com/zosconnect/zowe-cli-zosconnect-plugin/files/7342179/zowe-10042021.1.log)

**Comment by crshnburn** [comment]
Hello, thank you for raising this issue.

The log snippets from the z/OS Connect EE Server indicate that the supplied username was not found in the configured registry which is why a security error is being returned to the CLI client.

Is it possible to confirm whether a password was used when getting the information in the browser and if it wasn't then try removing the username and password from the zosconnect profile and try the request again.

**Comment by DivergentEuropeans** [comment]
Hello, thank you for your help. It appears that my node.js and npm compatibility was wrong. After uninstalling, and then letting node.js re-install both by node.js and npm version, the command worked as intended
